### ISSUE TITLE
Document and fix up query parameters and valid query parameter values / ranges.

### ISSUE THREAD

**Issue by MatthewHink** [vapor-ware/synse-server#101]
## Description
It's not obvious what query parameters are valid on every route.
You have to read the code to find out.
They get changed around and deprecated without comment or testing.
There are no examples showing what might be expected.

Impetus is this change: https://github.com/vapor-ware/synse-server/pull/96/files#diff-17f57b682366acd0bad5e60d91375623R115

Above should change to rpm to set_speed_rpm and percent to set_speed_percent. Sooner or later we could introduce another query parameter in units of rpm or another in units of percent. The set_speed_ prefix at least gives a clue that we are setting current speed.

Examples:
reset_speed_rpm (The speed to run the fan after controller reset)
watchdog_speed_rpm (The speed to run the fan after when the watchdog kicks in)
Likewise with percent. (reset_speed_percent, watchdog_speed_percent)

## Related Issues
- 

## Close Criteria
-

**Comment by edaniszewski** [comment]
between #109 and #105, would you consider this particular issue fixed, or is there additional work that should happen

**Comment by MatthewHink** [comment]
I need to look at this. Self assigned.

**Comment by edaniszewski** [comment]
Closing this. Since this was opened, a bunch of work was done to validate query params, error when invalid query params were given, error when query params are given but unsupported by the route, and the API docs were updated to document all current query params.
