### ISSUE TITLE
make all timestamps the same format

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-server#103]
## Description
not all timestamps are returned in the same format.

test
```json
{
  "status":"ok",
  "timestamp":"2018-03-23 14:06:40.147079"
}
```

read
```json
{
  "type":"temperature",
  "data":{
    "temperature":{
      "value":81.0,
      "timestamp":"2018-03-23T14:05:31.6192819Z",
      "unit":{
        "symbol":"C",
        "name":"degrees celsius"
      }
    }
  }
}
```

**Comment by edaniszewski** [comment]
https://stackoverflow.com/a/8556555

**Comment by MatthewHink** [comment]
Side thing. Are all timestamps UTC? Sites will be in different places and could be distributed at some point.

**Comment by edaniszewski** [comment]
Yes - for now all timestamps are UTC. I've looked into timezoning on timestamps, but it doesn't seem all that straightforward, so I just left it as UTC for now. We can definitely work towards getting proper time zone support in the future.
