### ISSUE TITLE
fan_sensors route. Sensors come in in random order.

### ISSUE THREAD

**Issue by MatthewHink** [vapor-ware/synse-server#116]
## Description
Likely related to https://github.com/vapor-ware/synse-server/issues/114

We used to have them ordered by VEC and by configuration order.

This affects the ability or auto_fan to get the plots we used to since columns no longer line up with specific sensors. Need to check if order differs across scan or fan_sensors calls on the same chamber.

## Related Issues
- 

## Close Criteria
-

**Comment by edaniszewski** [comment]
the fan sensors route is meant to be temporary until we can come up with a more permanent solution (at some point in the future), so modifying it to suit our needs in any way is perfectly fine to me. if we want it sorted, it can be sorted. should it be sorted with the `rack` as primary key, `board` as secondary key and `device` as tertiary key?
