### ISSUE TITLE
Public PR's Fail

### ISSUE THREAD

**Issue by timfallmk** [vapor-ware/synse-server#23]
## Description
Public PR's will always fail CircleCI due to a lack of permissions for non-org users. The problem lies in use of a private docker hub image (`vapor-ware/build-base`) which requires a login to pull. Users that belong to `vapor-ware` in GitHub (and have the correct scope) will get the necessary image, but outside users will not.

## Related Issues
- #21 

## Close Criteria
- Public PR builds should not automatically fail

## Notes
Ideally we shouldn't be using private resources in public repos.

**Comment by MatthewHink** [comment]
No Tim. We had CI. It got changed to Circle CI. Your problem. Sorry.

**Comment by MatthewHink** [comment]
Assigned to you.
