### ISSUE TITLE
Emulator support for other devices.

### ISSUE THREAD

**Issue by grampelberg** [vapor-ware/synse-server#29]
## Description

As part of working to integrate `synse-graphql` with the ongoing 2.0 work, the emulator will need to be extended a little bit. It appears that the missing devices currently are:

- pressure
- airflow
- humidity

**Comment by edaniszewski** [comment]
Makes sense. As a more general statement on this, I think the emulator should support every _device type_ that we support for real, but doesn't need to support all flavors of it. E.g., we don't need a 'MAX11608' thermistor and 'MAX11610' thermistor modeled here, but we should have a temperature device.

**Comment by pyronicide** [comment]
Yup, from my perspective, I just need something that gives me the endpoints and responses.

**Comment by grampelberg** [comment]
@edaniszewski doesn't look like the `vaporio/synse-server:2.0.0` image has been updated. Should I be using something different?

**Comment by edaniszewski** [comment]
oh -- right. I removed the image build/push from CI when I was fixing it up, so this didn't push anew. I'll push a new 2.0.0 build manually right now.

**Comment by edaniszewski** [comment]
should be updated now
