### ISSUE TITLE
add a "device" route as an alias for the "scan" route

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-server#309]
We can keep the 'scan' in, but it seems to make sense to alias a `/device` route to it as well.

This way the interface is a bit more RESTFUL, e.g.

*Get all devices (scan)*
```
GET localhost:5000/v3/device
```

*Read from a device*
```
GET localhost:5000/v3/device/1234
```

*Write to a device*
```
POST localhost:5000/v3/device/1234
```

**Comment by MatthewHink** [comment]
Just keep in mind supportability issues, once it's added it should be supported or clients leave.
