### ISSUE TITLE
consideration: if data within the write context is empty, perhaps omit the field entirely

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-server#359]
e.g., if we issue a write and the reflected context is something along the lines of
```json
[
  {
    "id": "2b717ced-58ff-43dc-ab6f-d4c0c6008ebb",
    "device": "f041883c-cf87-55d7-a978-3d3103836412",
    "context": {
      "action": "color",
      "data": "f38ac2",
      "transaction": ""
    },
    "timeout": "30s"
  }
]
```

we could omit the empty transaction
```json
[
  {
    "id": "2b717ced-58ff-43dc-ab6f-d4c0c6008ebb",
    "device": "f041883c-cf87-55d7-a978-3d3103836412",
    "context": {
      "action": "color",
      "data": "f38ac2",
    },
    "timeout": "30s"
  }
]
```

not totally necessary, but reducing the amount of "empty" data does make it a bit more easy to parse visually.

this is open for discussion/opinions/thoughts

**Comment by marcoceppi** [comment]
The thing that tripped me up the most was the fact `transaction` was a blank string instead of null. I like the idea of omitting context that wasn't explicitly passed but I can see the value in having it explicitly stated. Especially now that I understand more what this field provides.

**Comment by MatthewHink** [comment]
Same here.

One way may be to make the context[transaction]: "id"

That would be plainer than empty, but may not be the best.
