### ISSUE TITLE
rework the dev/test cycle (and with it, simplify CI)

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-server#38]
## Description
The dev/test/lint cycle in 2.0 is still based on some old assumptions/requirements from 1.X -- because of the architectural changes and simplified test setup, we really don't *need* to be using containers for some of this stuff anymore. 

This is a bit of work, but should make development easier, and should make CI much cleaner since we won't have to deal with docker-in-docker-esque environments.

**Comment by edaniszewski** [comment]
as a note, this is also going to require some changes and cleanup for the tests themselves. in particular, being smarter about where test data is generated/stored.

**Comment by MatthewHink** [comment]
If there is a way for CI to do the same thing make ci does, I'm in.

Maybe not, but just saying.

**Comment by MatthewHink** [comment]
Also need to talk to you about the interface change for led write  (separate issue)
