### ISSUE TITLE
Separate code for I2C switch and device to truly support devices.

### ISSUE THREAD

**Issue by MatthewHink** [vapor-ware/synse-server#4]
Affects I2C devices that go through the PCA I2C switch.
We use the switch in our control system.
Customers are not likely to have it.

We would need to split out the switch code from the device code to truly support these devices for customers. We need the switch code for our control system.

Not high pri without a customer ask.

Affects:
max161XX thermistors.
PCA9632 LED
SDP610 Pressure

**Comment by edaniszewski** [comment]
closing this issue here - v1.x work is done, all work is moving to v2.0. in 2.0, this belongs at the plugin level.
