### ISSUE TITLE
Convert server API to k8s service and route connected clients properly

### ISSUE THREAD

**Issue by timfallmk** [vapor-ware/synse-server#85]
## Description
Currently synse-server is accessed via the local node address and `localhost` networking. It should be exposed as a kubernetes service, and thus have a proxied URI. This URI should also be usable by the clients, plugins, prometheus, etc.

## Related
- https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-services/
- https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/

**Comment by MatthewHink** [comment]
Sounds really cool to me. Thanks.

**Comment by edaniszewski** [comment]
closing - moved issue to appropriate repo for k8s setup
